using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Models;
using System.Collections.Generic;
using System.Linq;
namespace RazorPages.Pages
{
    public class librodetalleModel : PageModel
    {
        public Libro? Libro { get; set; }

        public IActionResult OnGet(int id)
        {
            var libros = new List<Libro>
            {
                new Libro { Id = 1, Titulo = "Piense y hágase rico", Autor = "Napoleon Hill",Anio = 1967, Descripcion = "Así de fácil: la riqueza y la realización personal están al alcance de todas aquellas personas que lo desean; basta simplemente con desvelar un secreto, el secreto del éxito. Esta nueva edición de este magnífico clásico está basada en la versión original del autor, y ha sido revisada y corregida ampliamente. Andrew Carnegie, Henry Ford, Theodore Roosevelt, Thomas Edison, Alexander Graham Bell y John D. Rockefeller, entre otros, son algunos de los entrevistados por Napoleon Hill para poder entender las entrañas de su éxito. Cualquiera que ponga en práctica sus principios y su filosofía, sin duda obtendrá todo aquello que desee en la vida.", Precio = 3500, Imagen = "so.jpg"},
                new Libro { Id = 2, Titulo = "El intercambio", Autor = "Jonh ", Anio = 1605, Descripcion = "Diez días para salvar una vida. Un segundo para ponerle fin. Hace quince años, Mitch McDeere esquivó a la muerte. Y a la mafia. Tras hacerse con diez millones de dólares y desaparecer, vio cómo sus enemigos acababan en la cárcel o en la tumba. Ahora Mitch y su mujer, Abby, viven en Manhattan, donde él se ha abierto camino hasta convertirse en socio del bufete más importante del mundo. Pero cuando su mentor en Roma le pide un favor que le llevará a Estambul y Trípoli, Mitch se ve inmerso en el centro de un siniestro complot con ramificaciones por todo el planeta y que una vez más pondrá en peligro a sus colegas, amigos y familia. Mitch se ha convertido en un experto en mantenerse un paso por delante de sus adversarios, pero ahora que el tiempo se está agotando, ¿será capaz de volver a lograrlo? Esta vez, no hay donde esconderse. Sobre la novela han dicho… «La secuela más ansiosamente esperada de la última década». Daily Express «Una actualización vertiginosa… Grisham, en su versión más clásica, intensifica el suspense». The Wall Street Journal «Una trama maravillosamente construida… Deja sin aliento al lector». Daily Mail «En esta novela Grisham nos regala la clase de narración hipnótica que siempre esperamos de él». Financial Times «Fascinante». Irish Independent «Los fans de Grisham lo van a devorar… La trama y el ritmo son frenéticos». Independente", Precio = 2800, Imagen = "Elintercambio.jpg"},
                new Libro { Id = 3, Titulo = "El arte de ser nosotros", Imagen = "Elarte.png", Autor = "Walter Riso", Anio = 2018, Descripcion = "El arte de ser nosotros es una guía práctica para aprender a amarnos a nosotros mismos y a vivir en armonía con los demás. Walter Riso nos ofrece herramientas y consejos para superar la dependencia emocional, fortalecer nuestra autoestima y construir relaciones saludables. A través de ejemplos y ejercicios, el autor nos invita a reflexionar sobre nuestras creencias y patrones de comportamiento, y nos anima a tomar el control de nuestra vida emocional. Este libro es una invitación a descubrir el poder del amor propio y a vivir una vida plena y auténtica.", Precio = 3200 },
                new Libro { Id = 4, Titulo = "Los ingenieros del caos" , Autor = "Jordi Borràs", Anio = 2020, Descripcion = "Los ingenieros del caos es una investigación periodística que revela cómo las redes sociales y las plataformas digitales han sido utilizadas para manipular la opinión pública y desestabilizar democracias en todo el mundo. Jordi Borràs nos lleva a un viaje por los entresijos de la desinformación, mostrando cómo grupos organizados y gobiernos autoritarios emplean tácticas de propaganda, bots y fake news para influir en elecciones y polarizar sociedades. A través de entrevistas con expertos y testimonios de víctimas, el autor expone las amenazas que enfrentamos en la era digital y nos invita a reflexionar sobre la importancia de la alfabetización mediática y la responsabilidad individual en la lucha contra la manipulación informativa.", Precio = 3000, Imagen = "1211.jpg"},
                new Libro { Id = 5, Titulo = "Deja de ser tu" , Autor = "Joe Dispenza", Anio = 2017, Descripcion = "Deja de ser tú es un libro que explora la conexión entre la mente y el cuerpo, y cómo podemos transformar nuestra vida cambiando nuestros pensamientos y emociones. Joe Dispenza nos guía a través de un proceso de autoconocimiento y crecimiento personal, enseñándonos a liberarnos de patrones limitantes y a crear una nueva realidad basada en la intención y la conciencia. A través de ejercicios prácticos y meditaciones, el autor nos invita a descubrir nuestro verdadero potencial y a vivir una vida más plena y satisfactoria.", Precio = 4000, Imagen = "ses.jpg"},
                new Libro { Id = 6, Titulo = "Viaje a el centro de la tierra" , Autor = "Julio Verne", Anio = 1864, Descripcion = "Viaje al centro de la Tierra es una novela de aventuras que narra la expedición del profesor Otto Lidenbrock, su sobrino Axel y su guía Hans Belker al interior del planeta. Siguiendo un antiguo manuscrito, los protagonistas descienden a través de un volcán en Islandia y se enfrentan a numerosos desafíos y peligros en su travesía por un mundo subterráneo lleno de maravillas naturales, criaturas prehistóricas y fenómenos extraordinarios. A lo largo de su viaje, los exploradores deben utilizar su ingenio y valentía para sobrevivir y descubrir los secretos ocultos en las profundidades de la Tierra.", Precio = 2500, Imagen = "tierra.jpg"},
                new Libro { Id = 7, Titulo = "GRAVITY FALLS DIARIO 3" , Autor = "Alex Hirsch", Anio = 2016, Descripcion = "Gravity Falls Diario 3 es un libro que recopila los misterios y secretos del pueblo ficticio de Gravity Falls, tal como se presentan en la serie animada del mismo nombre. Escrito por el creador de la serie, Alex Hirsch, el diario está lleno de ilustraciones, notas y pistas que revelan la historia oculta detrás de los personajes y eventos de la serie. A través de sus páginas, los lectores pueden explorar criaturas sobrenaturales, enigmas sin resolver y teorías conspirativas que hacen de Gravity Falls un lugar fascinante y lleno de aventuras.", Precio = 4500, Imagen = "diario.jpg"},
                new Libro { Id = 8, Titulo = "La niña del sombrero azul" , Autor = "Ana Alcolea", Anio = 2020, Descripcion = "La niña del sombrero azul es una novela juvenil que narra la historia de Lucía, una adolescente que descubre un misterioso sombrero azul en el desván de su abuela. A medida que Lucía investiga el origen del sombrero, se ve envuelta en una serie de aventuras que la llevan a descubrir secretos familiares, amistades inesperadas y el valor de la valentía y la perseverancia. A través de su viaje, Lucía aprende importantes lecciones sobre la identidad, la confianza en uno mismo y la importancia de seguir los propios sueños.", Precio = 2700, Imagen = "som.jpg"},
                new Libro { Id = 9, Titulo = "EL HIJO DE NEPTUNO ( LOS HEROES DEL OLIMPO )" , Autor = "Rick Riordan", Anio = 2012, Descripcion = "El hijo de Neptuno es la segunda entrega de la serie Los Héroes del Olimpo, escrita por Rick Riordan. La historia sigue a Percy Jackson, un semidiós hijo de Poseidón, que se encuentra en un campamento para semidioses romanos sin recuerdos de su pasado. Junto a sus nuevos amigos, Hazel Levesque y Frank Zhang, Percy emprende una peligrosa misión para salvar al mundo de una amenaza inminente: la resurrección de la diosa romana de la muerte, Proserpina. A lo largo de su aventura, los protagonistas enfrentan desafíos épicos, descubren secretos sobre sus orígenes y fortalecen sus lazos de amistad y lealtad.", Precio = 3800, Imagen = "nepa.jpg"},
                new Libro { Id = 10, Titulo = "AMANECER EN LA COSECHA ( LIBRO 5 DE LOS JUEGOS DEL HAMBRE )" , Autor = "Suzanne Collins", Anio = 2020, Descripcion = "Amanecer en la cosecha es el quinto libro de la serie Los Juegos del Hambre, escrita por Suzanne Collins. La historia continúa la saga de Katniss Everdeen, quien ahora debe enfrentarse a las consecuencias de su papel como símbolo de la rebelión contra el Capitolio. A medida que la guerra se intensifica, Katniss lucha por proteger a sus seres queridos y encontrar su lugar en un mundo devastado por el conflicto. Con giros inesperados y momentos emotivos, este libro explora temas de sacrificio, esperanza y la lucha por la libertad en medio de la adversidad.", Precio = 5000, Imagen = "juegos.jpg"},
                new Libro { Id = 11, Titulo = "Los gatos de fortuna", Autor = "Anny Duperey", Anio = 2000, Descripcion = "En este relato lleno de sensibilidad, Anny Duperey cuenta cómo los gatos, llegados a su vida casi siempre por azar, se convirtieron en compañeros indispensables. Cada uno de ellos marcó un momento importante de su existencia, acompañándola en la soledad, en la alegría o en la superación de dificultades. Con ternura y humor, la autora nos ofrece un homenaje a esos “gatos de fortuna” y a la huella que dejan en la vida de quienes los acogen", Precio = 14500, Imagen = "gatosFortuna.jpg" },
                new Libro { Id = 12, Titulo = "El laberinto en llamas (Las pruebas de apolo libro 3)", Autor = "Rick Riordan", Anio =2018 , Descripcion = "Con la ayuda de algunos amigos semidioses, Lester se las ha apañado para sobrevivir a las dos primeras pruebas: una en el Campamento Mestizo y la otra en Indianápolis, donde Meg recibió la profecía oscura. Las palabras que pronunció sentada en el Trono de la Memoria revelaron que un dream team de tres emperadores romanos supervillanos planea atacar el Campamento Júpiter. Mientras Leo vuela a toda velocidad para alertar el Campamento Romano, Lester y Meg deberán cruzar el Laberinto para encontrar al tercer emperador (y a un Oráculo que habla con juegos de palabras) en algún punto de suroeste de América. Por suerte, había un verso en la profecía que les da un poco de esperanza: Solo el guía ungulado sabe cómo no perderse. Está claro que van a tener un sátiro que los acompañe y Meg sabe exactamente a quién tiene que pedir este favorcito.", Precio = 25600 , Imagen = "ñasss.jpg" },
                new Libro { Id = 13, Titulo = "Un reino de promesas malditas", Autor = "Lexi Ryan", Anio = 2022, Descripcion = "Brie haría cualquier cosa antes de hacer un trato con las hadas; la muerte es preferible a sus viles planes. Pero cuando su hermana es secuestrada por el sadico rey de la Corte Unseelie, no hay nada que Brie no haría para poder recuperarla, incluso hacer un trato con el propio rey para robar tres reliquias mágicas de la corte rival. Obtener acceso sin restricciones a la Corte Seelie es más fácil de decir que de hacer. La única opción de Brie es hacerse pasar por una potencial novia para el Principe Ronan, el principe seelie que no es tan malvado como ella pensaba. Reacia a dejar que su corazón la distraiga, acepta la ayuda de una banda de unseelies marginados con su propia agenda secreta. Pero cuando Brie pasa tiempo con su misterioso lider, Finn, se encuentra luchando para resistir su seductor encanto. Atrapada entre dos peligrosas cortes, Brie debe decidir en quien confía con su lealtad… y con su corazón.", Precio =16300 , Imagen = "mald.jpg" },
                new Libro { Id = 14, Titulo = "La espada de Kuromori", Autor = "Jason Rohan", Anio = 2014, Descripcion = "Un chico llamado Kenny Blackwood llega a Tokio para pasar el verano con su padre. Todo parece indicar que serán unas vacaciones comunes y corrientes. Sin embargo, muy pronto se ve envuelto en una peligrosa e inesperada misión que pondrá a prueba su valor e inteligencia. Este joven héroe descubre que posee poderes especiales y que a su alrededor hay seres mitológicos que inciden en los acontecimientos cotidianos. Kenny deberá encontrar la legendaria Espada de Cielo, la cual le servirá para salvar su vida y evitar una guerra. Con esta arma enfrentará a un conjunto de terroríficas criaturas que no dudarán en matarlo si él les da la oportunidad. Su única ayuda será Kiyomi, una sarcástica y ruda chica.", Precio = 11800, Imagen = "esp.jpg" },
                new Libro { Id = 15, Titulo = "El veneno del poder", Autor = "Gabriela Cerruti", Anio =2025, Descripcion = "El poder del veneno es un thriller político de Gabriela Cerruti que explora la intimidad del poder en Argentina. Sigue al presidente Salvador Gómez, un mandatario débil en medio de una crisis económica y un escándalo personal por su divorcio y nueva relación. La trama se desencadena con una muerte sospechosa en su departamento privado, que podría ser suicidio, accidente o asesinato. La novela, además de la intriga, ofrece una mirada detallada y realista de los entresijos del poder —desde la Casa Rosada hasta las reuniones políticas—, mostrando sus bajezas y lealtades. La autora, con su experiencia periodística y política, describe con agudeza este mundo desde adentro.", Precio = 28699, Imagen = "veneno.jpg" },
                new Libro { Id = 16, Titulo = "Elon Musk", Autor = "Walter Isaacson", Anio = 2023, Descripcion = "Elon Musk de Walter Isaacson es una biografía que explora el impacto de los traumas infantiles —acoso escolar y abuso paterno— en la formación de la personalidad obsesiva y volátil del magnate. Analiza cómo estas experiencias impulsaron sus éxitos con Tesla y SpaceX, pero también sus actitudes impredecibles y la polémica compra de Twitter. Con acceso privilegiado a su vida, el libro cuestiona si los demonios personales de Musk son el precio inevitable de su genio innovador.", Precio = 25899, Imagen = "elon.jpg" },
                new Libro { Id = 17, Titulo = "El crimen de año nuevo", Autor = "Daniel Balmaceda", Anio = 2025, Descripcion = "En 1880, Buenos Aires ya no era aquella Gran Aldea apacible, sacudida apenas por el traqueteo esporádico de un tranvía o un carruaje. Una cuarta parte de sus habitantes eran inmigrantes alojados en pensiones, aferrados al sueño de un futuro mejor. En el corazón de ese deslumbrante y desigual escenario urbano, comienza a gestarse una tragedia. En un conventillo del barrio Norte, un crimen quiebra la frágil convivencia de los inquilinos y estremece a la colectividad napolitana. El cuerpo yace en el patio, y a su alrededor se multiplican las conjeturas: ¿venganza, celos, ajuste de cuentas, rencor? Todos parecen tener algo que ocultar. Reconstruir lo sucedido será una travesía entre indicios, secretos y giros inesperados. Los personajes son piezas de un rompecabezas que el lector deberá armar, dudando de cada uno. ¿Quién es la víctima? ¿Qué misterios se ocultan tras las máscaras que impone el delito? Rescatada con maestría por Daniel Balmaceda a partir de documentos olvidados, esta historia real y vertiginosa, narrada con suspenso y puntillosa destreza, desempolva huellas del pasado para retratar una época convulsa, inaugural y profundamente reveladora de la idiosincrasia argentina.", Precio = 32400, Imagen = "hhhh.jpg" },
                new Libro { Id = 18, Titulo = "Alma de gato", Autor = "Ruth Berger", Anio = 2011, Descripcion = "Alma de gato de Ruth Berger es una colección de 78 historias que celebran el vínculo único entre humanos y gatos. A través de relatos conmovedores, divertidos e inspiradores, el libro captura la esencia de la conexión felina: desde anécdotas cotidianas como gatos que rompen objetos o evaden vacunas, hasta momentos profundos donde estos animales acompañan a sus dueños en superar crisis o enfermedades.Con un tono cálido y reflexivo, la autora destaca el amor incondicional, la complicidad y la intuición de los felinos, mostrando cómo transforman la vida de las personas. Ideal para quienes creen en el alma especial de los gatos y su impacto en nuestras vidas.", Precio = 17299, Imagen = "almaGatoo.png" },
                new Libro { Id = 19, Titulo = "Bajo la misma estrella", Autor = "John Green", Anio = 2012, Descripcion = "Este libro narra la historia de Hazel Grace Lancaster, una adolescente de 16 años que sobrevive gracias a un tratamiento experimental contra el cáncer de tiroides, y Augustus Waters, un joven carismático y optimista que perdió una pierna por osteosarcoma. Ambos se conocen en un grupo de apoyo para pacientes oncológicos y, a pesar de las circunstancias adversas, inician una relación llena de humor, inteligencia y amor profundo. Juntos emprenden un viaje hacia Ámsterdam para cumplir el deseo de Hazel de conocer a su escritor favorito, enfrentándose a preguntas sobre la vida, la muerte, el legado y el significado de existir.", Precio = 22499, Imagen = "mismaEstrella.jpg" },
                new Libro { Id = 20, Titulo = "Yo antes de ti", Autor = "Jojo Moyes", Anio = 2012, Descripcion = "El libro sigue la vida de Louisa Clark, una joven alegre y excéntrica que pierde su trabajo en una cafetería y acepta un trabajo como cuidadora de Will Traynor, un hombre exitoso y aventurero que quedó paralítico tras un accidente. A pesar de sus personalidades opuestas y iniciales fricciones, ambos desarrollan una conexión profunda que transforma sus vidas. Lou se propone mostrar a Will que la vida aún puede valer la pena, pero él arrastra una herida emocional que pondrá a prueba su relación y los llevará a enfrentarse a decisiones imposibles sobre el amor, la libertad y el derecho a elegir.", Precio = 26699, Imagen = "antesDeTi.jpg" }
            };

            Libro = libros.FirstOrDefault(l => l.Id == id);

            if (Libro == null)
            {
                return RedirectToPage("/Index");
            }

            return Page();
        }
    }
}
